### ISSUE TITLE
pip install yields error

### ISSUE THREAD

**Issue by remiadon** [MusicLang/musiclang#1]
running
```bash
pip install musiclang
```
I get 

ERROR: Cannot install musiclang==0.0.1, musiclang==0.0.2, musiclang==0.5.2, musiclang==0.5.3, musiclang==0.5.4 and musiclang==0.5.5 because these package versions have conflicting dependencies.

python version: 3.9.12
pip version: 21.2.4
processor : Apple M1

**Comment by floriangardin** [comment]
It is hard to see what is causing this but have you tried to install it on an empty virtual env ?
Otherwise do you have a message with more details on what are the conflicting dependencies ?

**Comment by floriangardin** [comment]
Hello @remiadon I removed a lot of useless dependencies in the 0.7.1 version and removed the other versions from Pypi,  combined with the previous answer it should probably fix your issue.

**Comment by remiadon** [comment]
I will try again then
